[SERVICE]
    Flush        1
    Log_Level    info
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2020

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[OUTPUT]
    Name         loki
    Match        dpdms.*
    Host         loki
    Port         3100
    Labels       job=dpdms,container=$container_name,stream=$source
    Line_Format  json
