package zw.ac.uz.dpdms.hazard;
import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import jakarta.validation.Valid; import java.util.*; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.security.oauth2.jwt.Jwt; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/incidents") public class IncidentController {
 private final IncidentRepository incidents; private final AuditRepository audits; private final HazardAccess access; private final HazardProperties props; private final ObjectMapper json;
 public IncidentController(IncidentRepository i,AuditRepository a,HazardAccess x,HazardProperties p,ObjectMapper j){incidents=i;audits=a;access=x;props=p;json=j;}
 @GetMapping public List<Incident> list(@AuthenticationPrincipal Jwt jwt){access.read(jwt); if(access.national(jwt)) return incidents.findByStatus(IncidentStatus.APPROVED); if("RECORDER".equals(jwt.getClaimAsString("role"))) return incidents.findByReporterAndWard(jwt.getSubject(),jwt.getClaimAsString("ward")); return incidents.findAll();}
 @GetMapping("/{id}") public Incident one(@PathVariable Long id,@AuthenticationPrincipal Jwt jwt){access.read(jwt); Incident x=get(id); if(x.status!=IncidentStatus.APPROVED&&!x.reporter.equals(jwt.getSubject())&&!"SUPERVISOR".equals(jwt.getClaimAsString("role"))) throw new org.springframework.security.access.AccessDeniedException("403: incident is not approved"); return x;}
 @PostMapping public ResponseEntity<Incident> create(@Valid @RequestBody IncidentRequest r,@AuthenticationPrincipal Jwt jwt){access.recorder(jwt,r.ward()); validate(r); Incident x=apply(new Incident(),r); x.status=IncidentStatus.PENDING; incidents.save(x); audit(x,jwt,"CREATED","Submitted for approval"); return ResponseEntity.status(HttpStatus.CREATED).body(x);}
 @PutMapping("/{id}") public Incident update(@PathVariable Long id,@Valid @RequestBody IncidentRequest r,@AuthenticationPrincipal Jwt jwt){access.recorder(jwt,r.ward()); Incident x=get(id); if(!x.reporter.equals(jwt.getSubject())||x.status==IncidentStatus.APPROVED) throw new org.springframework.security.access.AccessDeniedException("403: cannot edit this incident"); validate(r); apply(x,r); incidents.save(x); audit(x,jwt,"UPDATED","Recorder updated incident"); return x;}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(@PathVariable Long id,@AuthenticationPrincipal Jwt jwt){Incident x=get(id); access.recorder(jwt,x.ward); if(!x.reporter.equals(jwt.getSubject())||x.status==IncidentStatus.APPROVED) throw new org.springframework.security.access.AccessDeniedException("403: cannot delete this incident"); incidents.delete(x); audit(x,jwt,"DELETED","Recorder deleted draft");}
 @PostMapping("/{id}/transition") public Incident transition(@PathVariable Long id,@Valid @RequestBody TransitionRequest r,@AuthenticationPrincipal Jwt jwt){access.supervisor(jwt); Incident x=get(id); if(r.status()==IncidentStatus.PENDING) throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Cannot transition to PENDING"); x.status=r.status(); incidents.save(x); audit(x,jwt,r.status().name(),r.reason()); return x;}
 @GetMapping("/{id}/audit") public List<AuditEntry> audit(@PathVariable Long id,@AuthenticationPrincipal Jwt jwt){access.read(jwt); return audits.findByIncidentIdOrderByActedAtAsc(id);}
 private Incident get(Long id){return incidents.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private Incident apply(Incident x,IncidentRequest r){x.ward=r.ward();x.district=r.district();x.province=r.province();x.occurredAt=r.occurredAt();x.reporter=r.reporter();x.severity=r.severity();x.latitude=r.latitude();x.longitude=r.longitude();try{x.indicatorsJson=json.writeValueAsString(r.indicators());}catch(JsonProcessingException e){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid indicators");}return x;}
 private void validate(IncidentRequest r){for(String key:props.requiredIndicators())if(!r.indicators().containsKey(key)||r.indicators().get(key)==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Missing required indicator: "+key);}
 private void audit(Incident x,Jwt j,String action,String detail){AuditEntry a=new AuditEntry();a.incidentId=x.id;a.actor=j.getSubject();a.action=action;a.detail=detail;audits.save(a);}
}
