package zw.ac.uz.dpdms.hazard;
import static org.junit.jupiter.api.Assertions.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.oauth2.jwt.Jwt;
class HazardAccessTest { private final HazardAccess access=new HazardAccess(new HazardProperties("FLOOD",List.of())); private Jwt jwt(String role,String hazard,String ward){return new Jwt("test",Instant.now(),Instant.now().plusSeconds(60),Map.of("alg","none"),Map.of("sub","user", "role",role,"hazard",hazard,"ward",ward));}
 @Test void hazardScopedRecorderCannotWriteToOtherHazardsOrWards(){assertThrows(AccessDeniedException.class,()->new HazardAccess(new HazardProperties("DROUGHT",List.of())).recorder(jwt("RECORDER","FLOOD","Ward 1"),"Ward 1"));assertThrows(AccessDeniedException.class,()->access.recorder(jwt("RECORDER","FLOOD","Ward 1"),"Ward 2"));}
 @Test void allHazardRecorderAndSupervisorAreDeniedByDefault(){var recorder=jwt("RECORDER","ALL","Ward 1");var supervisor=jwt("SUPERVISOR","ALL","");var drought=new HazardAccess(new HazardProperties("DROUGHT",List.of()));assertThrows(AccessDeniedException.class,()->drought.read(recorder));assertThrows(AccessDeniedException.class,()->drought.recorder(recorder,"Ward 1"));assertThrows(AccessDeniedException.class,()->drought.read(supervisor));assertThrows(AccessDeniedException.class,()->drought.supervisor(supervisor));}
 @Test void allHazardDemoScopesMayBeEnabledExplicitly(){var recorder=jwt("RECORDER","ALL","Ward 1");var supervisor=jwt("SUPERVISOR","ALL","");var demo=new HazardAccess(new HazardProperties("DROUGHT",List.of(),true));assertDoesNotThrow(()->demo.recorder(recorder,"Ward 1"));assertDoesNotThrow(()->demo.supervisor(supervisor));}
 @Test void nationalIsReadOnlyAcrossHazards(){assertDoesNotThrow(()->access.read(jwt("NATIONAL","", ""))); assertThrows(AccessDeniedException.class,()->access.supervisor(jwt("NATIONAL","", "")));}
 @Test void provincialAdministratorCanReadAllHazardsOnlyWithProvinceScope(){var provincial=new Jwt("test",Instant.now(),Instant.now().plusSeconds(60),Map.of("alg","none"),Map.of("sub","user","role","PROVINCIAL_ADMIN","hazard","ALL","ward","","province","Mashonaland Central"));assertDoesNotThrow(()->new HazardAccess(new HazardProperties("DROUGHT",List.of())).read(provincial));assertThrows(AccessDeniedException.class,()->access.read(jwt("PROVINCIAL_ADMIN","FLOOD","")));}
}
